# Diffold 训练配置文件示例

# 数据配置
data:
  data_dir: "./RNA3D_DATA"
  batch_size: 4
  max_sequence_length: 256
  num_workers: 4
  use_msa: true
  fold: 0  # 交叉验证折数 (0-9)

# 模型配置
model:
  rhofold_checkpoint: "./pretrained/model_20221010_params.pt"

# 训练配置
training:
  num_epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.00001
  grad_clip_norm: 1.0
  warmup_steps: 1000  # 预热步数（基于step而不是epoch）
  
  # 调度器配置
  scheduler_type: "cosine"  # "cosine", "plateau"
  patience: 10
  
  # 验证配置
  validate_every: 1
  early_stopping_patience: 20

# 输出配置
output:
  output_dir: "./output"
  checkpoint_dir: "./checkpoints"
  save_every: 5
  keep_last_n_checkpoints: 5

# 设备配置
device:
  device: "auto"  # "auto", "cpu", "cuda"
  mixed_precision: true

# 测试配置
test:
  test_mode: false
  test_samples: 10
  test_epochs: 5 